import { primary_color, secondary_color, accent_color } from '../../style/_color'

export default ({
  CustomAdd: {
    backgroundColor: secondary_color,
    color: 'white',
    borderRadius: '0px',
    margin: '0px 10px 0px 5px',
    textTransform: 'capitalize',
  },
  Add: {
    backgroundColor: primary_color,
    color: 'white',
    borderRadius: '0px',
    padding: '2px 15px',
    margin: '0px',
    minWidth: '5px',
    minHeight: '37px',
    textTransform: 'capitalize',
  },
  Summary: {
    background: accent_color,
    color: 'white',
    minHeight: '40px',
    minWidth: '40px',
    padding: '0px',
    borderRadius: '0px',
    margin: '5px',
  },
  WorkList: {
    backgroundColor: primary_color,
    fontSize: '13px',
    color: 'white',
    borderRadius: '0px',
    padding: '5px 10px',
    margin: '5px',
    minWidth: '5px',
    minHeight: '25px',
    textTransform: 'capitalize',
  },
  default: {
    background: accent_color,
    color: 'white',
    minHeight: '40px',
    minWidth: '40px',
    padding: '0px',
    borderRadius: '0px',
    margin: '5px',
  },
  Report: {
    background: primary_color,
    color: secondary_color,
    minHeight: '35px',
    minWidth: '35px',
    padding: '0px',
    borderRadius: '0px',
    margin: '0px',
    border: '0.5px solid white',
  },
  ReportRaised: {
    color: 'white',
  },
})
