export default ({
  CustomAdd: {
    backgroundColor: '#919191',
    color: 'white',
    borderRadius: '0px',
    padding: '2px 15px',
    margin: '0px 10px 0px 5px',
    textTransform: 'capitalize',
  },
  Add: {
    backgroundColor: '#505050',
    color: 'white',
    borderRadius: '0px',
    padding: '2px 15px',
    margin: '0px',
    minWidth: '5px',
    minHeight: '37px',
    textTransform: 'capitalize',
  },
  Summary: {
    background: '#cfcfcf',
    color: 'white',
    minHeight: '40px',
    minWidth: '40px',
    padding: '0px',
    borderRadius: '0px',
    margin: '5px',
  },
  WorkList: {
    backgroundColor: '#505050',
    fontSize: '13px',
    color: 'white',
    borderRadius: '0px',
    padding: '5px 10px',
    margin: '5px',
    minWidth: '5px',
    minHeight: '25px',
    textTransform: 'capitalize',
  },
  default: {
    background: '#cfcfcf',
    color: 'white',
    minHeight: '40px',
    minWidth: '40px',
    padding: '0px',
    borderRadius: '0px',
    margin: '5px',
  },
  Report: {
    background: '#505050',
    color: '#919191',
    minHeight: '35px',
    minWidth: '35px',
    padding: '0px',
    borderRadius: '0px',
    margin: '0px',
    border: '0.5px solid white',
  },
  ReportRaised: {
    color: 'white',
  },
})
